apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frames-onprem

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - triton/deployment.yaml
  - triton/service.yaml
  - tracker/deployment.yaml
  - tracker/service.yaml
  - qdrant/deployment.yaml
  - qdrant/service.yaml
  - qdrant/pvc.yaml
  - minio/deployment.yaml
  - minio/service.yaml
  - minio/pvc.yaml
